---

# - name: install network-scripts
#   yum:
#     name: "{{ packages }}"
#     state: present
#     update_cache: yes
#   vars:
#     packages:
#      - network-scripts

- name: set dummy module configuration
  copy:
    content: "dummy"
    dest: "/etc/modules-load.d/dummy.conf"
    mode: 0644
    owner: root
    group: root

- name: enable systemd-modules-load.service
  service:
    name: systemd-modules-load
    state: restarted
    enabled: yes
  when: not dummy_role_debug

- name: set dummy module configuration
  copy:
    content: "options dummy numdummies={{ dummy_number }}"
    dest: "/etc/modprobe.d/dummy.conf"
    mode: 0644
    owner: root
    group: root

- name: add the dummy module
  modprobe:
    name: dummy
    state: present
    params: "numdummies={{ dummy_number }}"
  when: not dummy_role_debug

- name: ensure network-scripts directory exists
  file:
    path: /etc/sysconfig/network-scripts
    state: directory
    mode: 0755
    owner: root
    group: root

- name: kresd.conf files
  template:
    src: "kresd-network-dummy.conf.j2"
    dest: /etc/knot-resolver/kresd.conf.d/410-network-dummy.conf
    owner: root
    group: knot-resolver
    mode: 0640
  when: kresd_threads is number and kresd_max_threads is number
  notify:
    - kresd restart

- include_tasks: network.yml
  with_sequence: start=0 end={{ dummy_number - 1 }}
