---
- name: set dummy module configuration
  ansible.builtin.copy:
    content: dummy
    dest: /etc/modules-load.d/dummy.conf
    mode: "0644"
    owner: root
    group: root
  when: not dummy_role_debug

- name: enable systemd-modules-load.service
  ansible.builtin.service:
    name: systemd-modules-load
    state: restarted
    enabled: true
  when: not dummy_role_debug

- name: set dummy module configuration
  ansible.builtin.copy:
    content: options dummy numdummies={{ dummy_number }}
    dest: /etc/modprobe.d/dummy.conf
    mode: "0644"
    owner: root
    group: root
  when: not dummy_role_debug

- name: add the dummy module
  community.general.modprobe:
    name: dummy
    state: present
    params: numdummies={{ dummy_number }}
  when: not dummy_role_debug

- name: check if kresd.conf.d exists
  ansible.builtin.stat:
    path: /etc/knot-resolver/kresd.conf.d/
  register: dummy_kresd_conf_d
  changed_when: false

- name: kresd.conf files
  ansible.builtin.template:
    src: kresd-network-dummy.conf.j2
    dest: /etc/knot-resolver/kresd.conf.d/410-network-dummy.conf
    owner: root
    group: knot-resolver
    mode: "0640"
  when: dummy_kresd_conf_d.stat.isdir is defined and dummy_kresd_conf_d.stat.isdir

- ansible.builtin.include_tasks: network.yml
  with_sequence: start=0 end={{ dummy_number - 1 }}
