---

- name: check dummy variables
  ansible.builtin.assert:
    that:
      - dummy_number is number and dummy_number > 0
    quiet: true

- include_tasks: dummy.yml
  when: ansible_os_family == "RedHat"
