---


- name: dummy interface configuration
  template:
    src: templates/ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-dummy{{ item }}
    owner: root
    group: root
    mode: 0644
  register: dummy_network_script

- name: ferm configuration
  template: src=templates/ferm.j2 dest=/etc/ferm/ferm.d/1000-dummy{{ item }}.conf owner=root group=root mode=0600
  notify:
    - ferm restart

- name: dummy restart
  command: bash -c "ifdown dummy{{ item }} && ifup dummy{{ item }}"
  when: (dummy_role_debug|bool == false) and dummy_network_script.changed
