---
- name: dummy{{ item }} service configuration
  ansible.builtin.template:
    src: templates/dummy@.service
    dest: /usr/lib/systemd/system/dummy{{ item }}.service
    owner: root
    group: root
    mode: "0644"
  register: dummy_service
  when: not dummy_role_debug|bool

- name: dummy{{ item }} ferm variables
  ansible.builtin.template:
    src: templates/ferm-vars.j2
    dest: /etc/ferm/vars.d/1000-dummy{{ item }}.conf
    owner: root
    group: root
    mode: "0600"

- name: dummy{{ item }} ferm configuration
  ansible.builtin.template:
    src: templates/ferm.j2
    dest: /etc/ferm/ferm.d/9000-dummy{{ item }}-isolation.conf
    owner: root
    group: root
    mode: "0600"

- name: dummy{{ item }} enable
  ansible.builtin.systemd:
    name: dummy{{ item }}
    enabled: true
    daemon_reload: true
  when: not dummy_role_debug|bool

- name: dummy{{ item }} restart
  ansible.builtin.systemd:
    name: dummy{{ item }}
    state: restarted
    enabled: true
    daemon_reload: true
  when: (not dummy_role_debug|bool) and (dummy_ifcfg.changed or dummy_service.changed)
